### ISSUE TITLE
Support Custom Headers

### ISSUE THREAD

**Issue by ryanballa** [instanceofMA/arduino-fetch#2]
Hi, are custom headers supported? I tried adding one called "authKey" and got an error `'class Headers' has no member named 'authkey'`.

**Comment by instanceofMA** [comment]
Not yet! But I can add them till the weekend if it's not really urgent?

**Comment by ryanballa** [comment]
No rush, I was able to add the header I needed to the library to unblock myself.

**Comment by instanceofMA** [comment]
I have added support for custom headers using square-bracket notation:

```cpp
options.headers["authKey"] = "abcdefgh";
```

Thanks a lot for your feedback!
