### ISSUE TITLE
Great Idea

### ISSUE THREAD

**Issue by hpssjellis** [instanceofMA/arduino-fetch#4]
I like this concept. I will try it on Adafruit.io

**Comment by instanceofMA** [comment]
Did you just open an issue to tell me this library is a great idea?

**Comment by hpssjellis** [comment]
Yup. I will close it now. Not working on the Arduino PortentaH7, but I still like the idea.

**Comment by instanceofMA** [comment]
> Yup. I will close it now. Not working on the Arduino PortentaH7, but I still like the idea. 

What exactly do you like about it?

**Comment by hpssjellis** [comment]
My background is Javascript so I love fetch. Now I am using Arduino's. I am trying to access the adafruit site with the Arduino PortentaH7 using either http or MQTT but things are not going well.

This site I made gives some reference  

https://hpssjellis.github.io/my-examples-of-iot-platforms/public/index.html

I have everything working except the Arduino parts.
